Documentation/UserStories.md
Documentation/requirements.md

I looked into it and created User stories based on what should be done.

Create User Stories

---

group-collaboration/src/App.js
group-collaboration/src/components/Landing/index.js
group-collaboration/src/components/NewProject/form.js
group-collaboration/src/components/NewProject/index.js
group-collaboration/src/components/ProfileEditor/biographyEditor.js
group-collaboration/src/components/ProfileEditor/emailVerifier.js
group-collaboration/src/components/ProfileEditor/index.js
group-collaboration/src/components/ProfileEditor/nameEditor.js
group-collaboration/src/components/ProfileViewer/index.js
group-collaboration/src/components/Projects/index.js
group-collaboration/src/components/Session/context.js
group-collaboration/src/components/Session/index.js
group-collaboration/src/components/TopBar/index.js
group-collaboration/src/components/TopBar/nametag.js

Fix issue #27, along with some other related but undocumented issues.
This was due to an unnecessary abstraction of the firebase auth object into a 'session' object; which lagged behind in updates. Removing the abstraction fixed the problem.

Replace 'session' context with firebase.auth.currentUser

---

group-collaboration/src/components/Firebase/firebase.js
group-collaboration/src/components/NewProject/form.js
group-collaboration/src/components/NewProject/index.js
group-collaboration/src/components/Projects/index.js
group-collaboration/src/components/Projects/table.js

This PR refactors functionality of the Projects component.
1) Code that interacts with the Firestore is centralized in the Firebase class.
2) The markup for the Projects list been moved into its own component.

Refactor Projects Component

---

group-collaboration/src/App.js
group-collaboration/src/components/Firebase/firebase.js
group-collaboration/src/components/ProjectViewer/biographyEditor.js
group-collaboration/src/components/ProjectViewer/index.js
group-collaboration/src/components/Projects/styles.css
group-collaboration/src/components/Projects/table.js
group-collaboration/src/constants/routes.js

This PR adds a Project Details component to show details in an unconstrained space.
The Project Details component is accessed through the 'details' link in the Project List component.

Implemented Project Details component.

---

group-collaboration/.env.development

Add development config for WebDevAtlanta Firebase account.

Add env development config for Firebase.

---

group-collaboration/Makefile

Consolidate development knowledge in the Makefile.

A Makefile for common tasks.

---

group-collaboration/src/App.js
group-collaboration/src/components/NewProject/form.js
group-collaboration/src/components/ProfileEditor/biographyEditor.js
group-collaboration/src/components/ProfileViewer/index.js
group-collaboration/src/components/ProjectEditor/form.js
group-collaboration/src/components/ProjectViewer/index.js
group-collaboration/src/components/Projects/index.js
group-collaboration/src/components/Session/context.js
group-collaboration/src/components/Session/index.js
group-collaboration/src/components/Session/session.js
group-collaboration/src/components/TopBar/index.js

User sessions are now persisted through reloads.

Share/publish user auth through a React context.

---

group-collaboration/src/components/Firebase/firebase.js
group-collaboration/src/components/ProfileEditor/biographyEditor.js
group-collaboration/src/components/ProfileEditor/nameEditor.js
group-collaboration/src/components/ProfileViewer/index.js

DRY the profile loader/updater code.

Refactor profile loader/update code into Firebase context object.

---

group-collaboration/src/App.css
group-collaboration/src/App.js
group-collaboration/src/components/Firebase/firebase.js
group-collaboration/src/components/Landing/index.js
group-collaboration/src/components/NavDrawer/index.js
group-collaboration/src/components/ProjectEditor/index.js
group-collaboration/src/components/TopBar/index.js
group-collaboration/src/constants/styles.js

This PR implements a NavDrawer with buttons for Projects and Account pages.
This PR addresses issues #35 and #37.

Implement NavDrawer

---

group-collaboration/src/components/TopBar/nametag.js

Check for valid session before reading properties.

---

group-collaboration/src/components/Landing/index.js
group-collaboration/src/components/TopBar/index.js

Change all instances of 'login' to 'sign in'

---

group-collaboration/src/components/NewProject/form.js
group-collaboration/src/components/ProjectEditor/form.js

Changed reference to `uid` in `session` from `session.user.uid` to `session.uid`

Fixes #63 Fix reference to uid in session

---

group-collaboration/src/components/NewProject/form.js
group-collaboration/src/components/NewProject/index.js
group-collaboration/src/components/NewProject/style.css

Style New Project component Issue #49

---

group-collaboration/src/App.js
group-collaboration/src/components/NavDrawer/index.js
group-collaboration/src/components/Session/index.js
group-collaboration/src/components/Session/session.js

Correctly set session state when firebase currentUser is null.

---

group-collaboration/src/components/TopBar/index.js

The hamburger's opacity is now 0 when the drawer is open.

Hide hamburger when drawer open #45

---

group-collaboration/src/components/ProjectViewer/index.js

Fixes #72 Add labels to project viewer

---

group-collaboration/src/App.js
group-collaboration/src/components/Firebase/firebase.js
group-collaboration/src/components/ForgotPassword/form.js
group-collaboration/src/components/ForgotPassword/index.js
group-collaboration/src/components/SignIn/index.js
group-collaboration/src/components/SignIn/style.css
group-collaboration/src/constants/routes.js

- Add a new forgot password route
- Add link on sign in for to navigate to forgot password
- Add reset password functionality using firebase

Fixes #54 Add forgot password functionality

---

src/components/NavDrawer/index.js

Navdrawer uses routes.js constants

NavDrawer uses routes constants

---

package.json

A pull request birthed from the womb of ytest

Add abrie's postinstall githook

---

.prettierrc

This config matches 95% of the current HEAD.
If you prefer something else, speak now or forever hold your peace...

Fix #110 - add a config for Prettier.

---

.env.test
.gitignore
README.md
firebase.json
package.json
src/components/Firebase/firebase.js
src/components/Firebase/firebase.test.js
src/components/ProjectViewer/index.test.js
src/index.js
src/setupTests.js
yarn.lock

Refactored the Firebase class to be better suited for unit tests. Added tests for project, follower, message, and profile functionalities. The new tests validate the core backend logic using a local Firebase test server. See the updated README for how to instantiate the local Firebase server.

Unit test firebase functions

---

src/components/ProfileEditor/index.test.js

Admittedly, I'm unfamiliar with the act() call, among other things. Let me know if there's anything I need to fix!

Create smoke test for ProfileEditor #104
